title: Thermostat Controller
description: iPhone app to view and control your Venstar thermostat locally.
author:
  name: STUDIOJQ
  url: https://github.com/thestudiojq
github:
  repo: https://github.com/thestudiojq/thermostat-controller
version: 0.1.0
permalink: pretty
markdown: kramdown